### ISSUE TITLE
template_source file not found 

### ISSUE THREAD

**Issue by karstenmueller** [pendrica/chef-provisioning-azurerm#22]
Hi Stuart,

with Chef Development Kit version 1.0.3 and chef-provisioning-azurerm version 0.4.0 the template_source file was not found anymore. It works with ChefDK Version: 0.17.17 and chef-provisioning-azurerm version 0.3.4.

Did I miss something?

See error message in these logfiles:
[log_azurerem_0.3.4.txt](https://github.com/pendrica/chef-provisioning-azurerm/files/606320/log_azurerem_0.3.4.txt)
[log_azurerem_0.4.0.txt](https://github.com/pendrica/chef-provisioning-azurerm/files/606321/log_azurerem_0.4.0.txt)

**Comment by stuartpreston** [comment]
Yes, sorry about the breaking change but people complained that they could not specify a folder outside their cookbook path so in the example cookbooks that are now checked in, there's an example of the updated usage:

```
template_source "#{Chef::Config[:cookbook_path]}/arm-examples/templates/azuredeploy.json"
```

I checked in the examples but I need to get around to updating the readme too!  Sorry!

**Comment by stuartpreston** [comment]
I've updated the Readme now...

**Comment by karstenmueller** [comment]
Hi Stuart,

thanks a lot!

... but single quotes as in the README are not working. Instead 
~~~
template_source "#{Chef::Config[:cookbook_path]}/[...]"
~~~
seems to work. At least I got another error
~~~
    NoMethodError
    -------------
    undefined method `empty?' for nil:NilClass
 ~~~
which I can't explain.

**Comment by stuartpreston** [comment]
Apologies, yes your version is correct due to Ruby and string interpolation requirements.  Are you still blocked?  If so please can you post your recipe and the contents of stacktrace.out so I can make some suggestions.

**Comment by stuartpreston** [comment]
Please could you check you have added an ```environment``` parameter under the chef_extension attribute in your recipe as per the readme?  This got added in the latest version but I think there's a nil error bug when it is not set.

**Comment by karstenmueller** [comment]
Yes, I will add it!

**Comment by karstenmueller** [comment]
That did it, thanks! The environment parameter makes much sense.
